 because it is marked "can't reproduce" and has had no activity in the past week. Please comment with additional information, or this issue will be closed due to inactivity in one week.
          days-before-stale: 7
          days-before-close: 7
